version: "3.8"
services:
  mongo:
    image: mongo:6.0
    container_name: thalcare-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: thalcare-backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - DATABASE_NAME=thalcare_ai
      # Add your other env vars in a .env file or the environment here (OPENAI_API_KEY etc)

volumes:
  mongo-data:
